USE [GD1C2024]

/*SELECT DISTINCT
      PRODUCTO_NOMBRE,
      PRODUCTO_MARCA,
      PRODUCTO_PRECIO,
      TICKET_DET_PRECIO
FROM [gd_esquema].[Maestra]
WHERE PRODUCTO_PRECIO != TICKET_DET_PRECIO*/

SELECT DISTINCT
    s.id_subcategoria     as id_subcategoria,
    PRODUCTO_NOMBRE       as nombre,
    PRODUCTO_DESCRIPCION  as descripcion,
    PRODUCTO_PRECIO as precio_1,
    TICKET_NUMERO,
    PRODUCTO_MARCA        as marca
  FROM gd_esquema.Maestra

  JOIN REJUNTESA.categoria c ON PRODUCTO_CATEGORIA = c.categoria
  JOIN REJUNTESA.subcategoria s ON
      s.subcategoria = PRODUCTO_SUB_CATEGORIA AND
      s.id_categoria = c.id_categoria

  WHERE 
      PRODUCTO_SUB_CATEGORIA  is not null and
      PRODUCTO_NOMBRE         is not null and
      PRODUCTO_DESCRIPCION    is not null and
      PRODUCTO_PRECIO         is not null and
      PRODUCTO_MARCA          is not null

ORDER BY PRODUCTO_NOMBRE, PRODUCTO_MARCA, TICKET_NUMERO

SELECT TICKET_DET_PRECIO, TICKET_DET_CANTIDAD, TICKET_DET_TOTAL, PROMO_APLICADA_DESCUENTO, TICKET_NUMERO, REGLA_DESCRIPCION, REGLA_DESCUENTO_APLICABLE_PROD, PROMO_CODIGO FROM gd_esquema.Maestra
WHERE TICKET_DET_TOTAL is not null AND PROMO_APLICADA_DESCUENTO is not null
AND TICKET_DET_TOTAL < PROMO_APLICADA_DESCUENTO
ORDER BY TICKET_DET_PRECIO, TICKET_DET_CANTIDAD, TICKET_NUMERO ASC

--WHERE TICKET_NUMERO = 1351318368--1351426113--1351318349--1353722924--1352375255