USE [GD1C2024]

SELECT DISTINCT
    PRODUCTO_PRECIO, PROMO_APLICADA_DESCUENTO, TICKET_DET_CANTIDAD, TICKET_DET_TOTAL, TICKET_NUMERO
FROM [gd_esquema].Maestra
WHERE PRODUCTO_NOMBRE = 'Codigo:0131231312' AND PRODUCTO_MARCA = 'Marca N°013414124'
ORDER BY TICKET_DET_CANTIDAD