USE [GD1C2024]

SELECT
    PRODUCTO_PRECIO,
    TICKET_DET_CANTIDAD,
    TICKET_DET_TOTAL,
    PRODUCTO_NOMBRE,
    PROMO_APLICADA_DESCUENTO
FROM [gd_esquema].[Maestra]
WHERE TICKET_NUMERO = 1351318449