USE [GD1C2024]

/*
MUY RARO PROMOS PRECIOS NEGATIVOS?

SELECT
    PRODUCTO_NOMBRE, PRODUCTO_MARCA,
    PRODUCTO_PRECIO, TICKET_DET_CANTIDAD, TICKET_DET_TOTAL, PROMO_APLICADA_DESCUENTO, TICKET_SUBTOTAL_PRODUCTOS, TICKET_TOTAL_DESCUENTO_APLICADO, TICKET_TOTAL_DESCUENTO_APLICADO_MP, TICKET_TOTAL_TICKET
FROM gd_esquema.Maestra WHERE TICKET_NUMERO = 1351846683
ORDER BY PRODUCTO_NOMBRE, PRODUCTO_MARCA

SELECT
    PRODUCTO_PRECIO * TICKET_DET_CANTIDAD-PROMO_APLICADA_DESCUENTO
FROM gd_esquema.Maestra WHERE TICKET_NUMERO = 1351846683*/